"""Render every timeline README.md to a sibling index.html.

    ./.venv/Scripts/python.exe timeline/build.py

The markdown IS the source. HTML is generated, never hand-edited -- two hand-maintained copies of
the same table drift, and the one you are not looking at is the one that goes stale.
"""
import pathlib
import re

import markdown

ROOT = pathlib.Path(__file__).parent
CSS_DEPTH = {0: "assets/style.css", 1: "../assets/style.css"}

PAGE = """<!-- generated by timeline/build.py from {src} -- edit the markdown, not this file -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="{css}">
<div class="wrap">
<nav class="crumb">{crumb}</nav>
{body}
<footer>Generated from {src} &middot; BiBo ablation timeline</footer>
</div>
"""


def render(md_path):
    depth = 0 if md_path.parent == ROOT else 1
    text = md_path.read_text(encoding="utf-8")
    title = re.search(r"^#\s+(.*)$", text, re.M)
    title = title.group(1).strip() if title else md_path.parent.name

    html = markdown.markdown(text, extensions=["tables", "attr_list", "sane_lists"])
    # tables need their own scroll container so a wide row never scrolls the page sideways
    html = html.replace("<table>", '<div class="tablewrap"><table>').replace(
        "</table>", "</table></div>")
    # "01-optimizer/" reads well on GitHub but a bare directory href does not resolve under
    # file://, so point the generated HTML at the page itself.
    html = re.sub(r'href="([0-9]{2}-[a-z-]+)/"',
                  lambda m: 'href="%s/index.html"' % m.group(1), html)

    crumb = ('<span>BiBo ablation timeline</span>' if depth == 0 else
             '<a href="../index.html">&larr; timeline</a>'
             f'<span>{md_path.parent.name}</span>')

    out = md_path.with_name("index.html")
    out.write_text(PAGE.format(title=title, css=CSS_DEPTH[depth], crumb=crumb,
                               body=html, src=md_path.name), encoding="utf-8")
    return out


def main():
    made = [render(p) for p in sorted(ROOT.glob("*/README.md")) + [ROOT / "README.md"]]
    for m in made:
        print("wrote", m.relative_to(ROOT))
    print(f"{len(made)} pages")


if __name__ == "__main__":
    main()
